plugins:
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'sorbet/**/*'
    - 'vendor/**/*'

# Ban inline disable comments
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true


Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'leechtop_downloader.gemspec'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

# Justification: Testing CLI and IO state often requires multiple assertions per context.
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
