#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require 'leechtop_downloader'

LeechtopDownloader::CLI.start(ARGV)
