name: Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on semantic version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a GitHub Release
      id-token: write # Required for OIDC Trusted Publishing
    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.2"
          bundler-cache: true

      - name: Set Release Version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/VERSION = '.*'/VERSION = '$TAG_VERSION'/" lib/http_loader/version.rb

      - name: Setup Gem Signing
        env:
          GEM_PRIVATE_KEY: ${{ secrets.GEM_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.gem
          echo "$GEM_PRIVATE_KEY" > ~/.gem/gem-private_key.pem
          chmod 0600 ~/.gem/gem-private_key.pem

      - name: Build Gem
        run: gem build http_loader.gemspec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: "*.gem"
          generate_release_notes: true

      - name: Configure RubyGems Credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Publish to RubyGems
        run: gem push *.gem
